[package]
name = "rui3-at"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
no-std = true

[dependencies]
atat = { version = "0.18.0" }
embedded-hal = { version = "0.2.7" }
text_io = { version = "0.1.12" }
